first_name = input()
last_name = input()
age = int(input())
town = input()
print('You are {0} {1}, a {2}-years old person from {3}.'.format(first_name, last_name, age, town))

first_name = input()
last_name = input()
age = int(input())
town = input()
print('You are' + first_name + last_name + ', a ' + str(age) + '-years old person from ' + town + '.')